/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundraiseHowItWorksRouteImport } from './routes/fundraise.how-it-works'
import { Route as DonateSuccessRouteImport } from './routes/donate.success'
import { Route as DonateFailureRouteImport } from './routes/donate.failure'
import { Route as CampaignListRouteImport } from './routes/campaign.list'
import { Route as CampaignCreateRouteImport } from './routes/campaign.create'
import { Route as CampaignSlugRouteImport } from './routes/campaign.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'

const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraiseHowItWorksRoute = FundraiseHowItWorksRouteImport.update({
  id: '/fundraise/how-it-works',
  path: '/fundraise/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: '/donate/success',
  path: '/donate/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateFailureRoute = DonateFailureRouteImport.update({
  id: '/donate/failure',
  path: '/donate/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignListRoute = CampaignListRouteImport.update({
  id: '/campaign/list',
  path: '/campaign/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCreateRoute = CampaignCreateRouteImport.update({
  id: '/campaign/create',
  path: '/campaign/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignSlugRoute = CampaignSlugRouteImport.update({
  id: '/campaign/$slug',
  path: '/campaign/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/campaign/create': typeof CampaignCreateRoute
  '/campaign/list': typeof CampaignListRoute
  '/donate/failure': typeof DonateFailureRoute
  '/donate/success': typeof DonateSuccessRoute
  '/fundraise/how-it-works': typeof FundraiseHowItWorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/campaign/create': typeof CampaignCreateRoute
  '/campaign/list': typeof CampaignListRoute
  '/donate/failure': typeof DonateFailureRoute
  '/donate/success': typeof DonateSuccessRoute
  '/fundraise/how-it-works': typeof FundraiseHowItWorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/campaign/create': typeof CampaignCreateRoute
  '/campaign/list': typeof CampaignListRoute
  '/donate/failure': typeof DonateFailureRoute
  '/donate/success': typeof DonateSuccessRoute
  '/fundraise/how-it-works': typeof FundraiseHowItWorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/campaign/$slug'
    | '/campaign/create'
    | '/campaign/list'
    | '/donate/failure'
    | '/donate/success'
    | '/fundraise/how-it-works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/campaign/$slug'
    | '/campaign/create'
    | '/campaign/list'
    | '/donate/failure'
    | '/donate/success'
    | '/fundraise/how-it-works'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/categories'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/campaign/$slug'
    | '/campaign/create'
    | '/campaign/list'
    | '/donate/failure'
    | '/donate/success'
    | '/fundraise/how-it-works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  CampaignSlugRoute: typeof CampaignSlugRoute
  CampaignCreateRoute: typeof CampaignCreateRoute
  CampaignListRoute: typeof CampaignListRoute
  DonateFailureRoute: typeof DonateFailureRoute
  DonateSuccessRoute: typeof DonateSuccessRoute
  FundraiseHowItWorksRoute: typeof FundraiseHowItWorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraise/how-it-works': {
      id: '/fundraise/how-it-works'
      path: '/fundraise/how-it-works'
      fullPath: '/fundraise/how-it-works'
      preLoaderRoute: typeof FundraiseHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/success': {
      id: '/donate/success'
      path: '/donate/success'
      fullPath: '/donate/success'
      preLoaderRoute: typeof DonateSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/failure': {
      id: '/donate/failure'
      path: '/donate/failure'
      fullPath: '/donate/failure'
      preLoaderRoute: typeof DonateFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/list': {
      id: '/campaign/list'
      path: '/campaign/list'
      fullPath: '/campaign/list'
      preLoaderRoute: typeof CampaignListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/create': {
      id: '/campaign/create'
      path: '/campaign/create'
      fullPath: '/campaign/create'
      preLoaderRoute: typeof CampaignCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$slug': {
      id: '/campaign/$slug'
      path: '/campaign/$slug'
      fullPath: '/campaign/$slug'
      preLoaderRoute: typeof CampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  CampaignSlugRoute: CampaignSlugRoute,
  CampaignCreateRoute: CampaignCreateRoute,
  CampaignListRoute: CampaignListRoute,
  DonateFailureRoute: DonateFailureRoute,
  DonateSuccessRoute: DonateSuccessRoute,
  FundraiseHowItWorksRoute: FundraiseHowItWorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
